### PR TITLE
3 create file infrastructure

### LINKED ISSUE #3: create file infrastructure

### PR DESCRIPTION
**Pull request by tlcoles**
This is a:

- [ x] :sparkles: **New feature** - new behaviour has been implemented
- [ ] :bug: **Bug fix** - existing behaviour has been made to behave
- [ ] :recycle: **Refactor** - the behaviour has not changed, just the implementation
- [ ] :white_check_mark: **Test backfill** - tests for existing behaviour were added but the behaviour itself hasn't changed
- [ ] :gear: **Chore** - maintenance task, behaviour and implementation haven't changed

### Description

- **Purpose** - File infrastructure build. See the Slack channel report for details or see the commit comments.

### Reminder to reviewers

- **Pull request** - read the content of the PR itself (_Conversation_ tab) and consider the following questions:

  - Is the user story/ticket linked?
  - Does the description match the linked item?
  - Does the description tell you how to validate the work?
  - Does the build still work (_Checks_ tab)?
  - What approach would you take to meet this goal?

- **Code changes** - read through the changeset (_Files changed_ tab) and consider the following questions:

  - Do the code changes match the description?
  - Are there any changes that should not be part of this pull request (e.g. layout changes in files not related to the functionality)?
  - Do you understand what the changes are doing, how they meet the goal of the PR?
  - Does the approach to meeting those goals seem sensible? If it's not the one you thought of, is it significantly better or worse?
  - Is this well-structured code (consistent layout, comprehensible variable names, relatively small files)?

### CODE REVIEW

**Comment by nirmeet-baweja** [comment]
Here are few remarks on the PR - 

1. You need to do ```npm init``` in the project directory as well. Make sure you install the ```concurrently``` package that would allow us to run both client and server sides during development.
2. Delete the all files you have added in ```/client/src/components``` directory.
3. Delete the files you have added in ```/client/src/pages``` directory except for ```Home.js```.
4. From next time onwards follow the branch naming rules shared in slack channel, so that branch names are uniform across the project.

**Comment by tlcoles** [comment]
> 4. From next time onwards follow the branch naming rules shared in slack channel, so that branch names are uniform across the project.

We agreed to use the "create branch" function from GitHub Projects. Are you saying that each of the card tasks should be prefaced with feature, refactor, or fix?

**Comment by tlcoles** [comment]
> 2. Delete the all files you have added in ```/client/src/components``` directory.
> 
> 3. Delete the files you have added in ```/client/src/pages``` directory except for ```Home.js```.

I would like to understand this, so let's talk later in class.

**Comment by nirmeet-baweja** [comment]
> We agreed to use the "create branch" function from GitHub Projects. Are you saying that each of the card tasks should be prefaced with feature, refactor, or fix?

You don't have to rename a card or issue for that, you can chose a branch name while creating it.

**Comment by nirmeet-baweja** [comment]
> 



> > 2. Delete the all files you have added in `/client/src/components` directory.
> > 3. Delete the files you have added in `/client/src/pages` directory except for `Home.js`.
> 
> I would like to understand this, so let's talk later in class.

The component structure hasn't been finalised yet, including how will the css be handled? Will it be component wise or a global css file? Since these things haven't been decided that means the components you have created are not finalised and hence cannot be added to the main branch.
Similarly, the pages haven't been finalised. So, they can't be added to the main branch.

**Comment by tlcoles** [comment]
> The component structure hasn't been finalised yet
> Similarly, the pages haven't been finalised

I am looking at the project document and recalling our Monday meeting. These are the corresponding files to the project document. Let's discuss again this evening.

**Review by nirmeet-baweja — APPROVED** [review]

**Review by tornicke — APPROVED** [review]

**Pull request merged**
